Feature 123/mypage
Mojacknong/Mojacknong_Android pull request #134
Opened 2024-03-25 10:37 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #123

### 🍠 Summary
PR이 너무 늦었죠..ㅎㅎ
코드가 마음에 안들어서 로직 어떻게 짜야할지 계속 고민하다 보니 PR이 늦어졌습니다.
UI구현은 설정 탭 제외하고는 다 했습니다.
우선 아린님도 마이페이지 보고싶을 수도 있으니 PR 날립니다!
아직 수정하고 싶은 것도 많고 로직도 다시 짜고 싶은 것도 많아서 그거 고려해서 코드 봐주세요~

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information

2024-03-26 15:21 UTC, arinming requested changes
일단 요정도 리뷰 남기구 내일 이어서 남길게여..!
아무래도 63개 파일 한번에 리뷰하려니까 조금 힘들어서 ㅜ ㅜ 담부터 잘게잘게 나눠서 스크린별로, 아니면 컴포넌트 몇개 단위로 피알 바로바로 올려주시면 빠른 피드백 해드리겠씁니당 일단 제가 리뷰단 거 위주로 수정먼저 해주세욥

2024-03-26 15:21 UTC, arinming commented on assets/image/image_example_community2.png
이 이미지 삭제해야합니당!

2024-03-26 15:21 UTC, arinming commented on assets/image/img_diary1.png
요 이미지도 삭제해주세용

2024-03-26 15:21 UTC, arinming commented on assets/image/img_farmclub_lettuce.png
컨테이너 안에 있는 채소 그래픽은 백엔드에서 넘겨주기로 해서, 해당 이미지를 사용하는 것이 아니라 빈 컨테이너를 컴포넌트로 구현해놓고 서버 통신으로 이미지를 받아와야 합니당! 삭제해도 될 것 같아용

2024-03-26 15:21 UTC, arinming commented on assets/image/img_farmer.png
요 이미지랑 img_farmer.svg 둘 다 삭제해도 될 것 같아요! 실질적으로 안쓰고, 서버에서 통신으로 가져오면 될 것 같습니당.
빈 컨테이너로 구현해주시면 됩니다!

2024-03-26 15:21 UTC, arinming commented on assets/image/ic_farmclub.png
헉 해당 png는 132번 PR에서 ic_farm_club으로 svg로 추출해두었는데, 삭제해도 좋을 것 같아용

2024-03-26 15:21 UTC, arinming commented on assets/image/img_greenonion.png
이 이미지부터 해서 상추, 고추, 대파, 토마토, 깻잎 마찬가지로 모두 백엔드에서 보내줄 예정이라, 프론트에서는 구현 안하기로 했습니당! 삭제해주시고 컬러 컨테이너로 구현해주셔야 할 것 가탕용.

2024-03-26 15:21 UTC, arinming commented on assets/image/img_vegeresult1.png
이 이미지도 마찬가지로, 피그마 상 예시이고 굳이 저희쪽에서 구현할 필요 없이 컨테이너로 구현하는 것이 용량 최적화에 좋을 듯 합니당!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_page_screen.dart
> +class MyPageScreen extends ConsumerWidget {
MyPageScreen 깔끔하네요! 코드가 깔끔해서 굳이 ConsumerWidget일 필요 없이 StatelessWidget로 구현해도 좋을 것 같아요 ㅎㅎ

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_page_screen.dart
> +            height: 140,
MyPageInfo와 MyHistory를 SizeBox로 감싸고 height를 하드코딩하는 방법 말고 유연하게 padding 처리하는 거 어떨까욤?

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_farmclub_screen.dart
> +class FarmClubScreen extends StatelessWidget {
어라 파일명은 my_farmclub_screen인데, 클래스 명이 FarmClubScreen 이에요!
FarmClubScreen은 바텀네비게이션으로 해둬서, 중복되지 않게 파일명과 통일해주세욥

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_farmclub_screen.dart
> +      appBar: FarmClubAppBar(),
해당 부분도 MyFarmClubAppBar로 바꿔주세요!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
> +                      fontWeight: FontWeight.w600,
TextStyle은 FarmusThemeTextStyle로 지정해서 깔끔하게 통일해주세욤!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
> +                  text: '스텝 ',
이번주 회의 결과, 스텝 -> Step으로 전체적 라이팅을 변경하였습니다!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
> +                  text: step, // 외부에서 받아온 step 변수 사용
주석 정리해주세용!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
> +                const TextSpan(
요 부분은 Text가 아닌 Divider로 세로줄 구현 가능할까요?!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/my_certification_screen.dart
> +class MyCertificationScreen extends StatefulWidget {
여기는 StatelessWidget으로 바꿔주세용! Screen 파일들은 직관적으로 찾을 수 있게, my_page폴더에서 빼서 view 폴더 안에 바로 폴더링 해주세용~!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/my_certification_feed.dart
> +import 'package:intl/intl.dart'; // DateFormat을 사용하기 위해 추가
주석 삭제해주세여~

2024-03-26 15:21 UTC, arinming commented on assets/image/ic_arrow_left.svg
해당 이미지 ic_left.svg로 추가해두었습니당! 삭제해도 될 것 같네엽

2024-03-26 15:21 UTC, arinming commented on assets/image/image_example_community.png
커뮤니티 없어서 안쓰는 이미지입니다!

2024-03-26 15:21 UTC, arinming commented on lib/main.dart
> +import 'package:farmus/view/my_page/vege_history/vege_history_screen.dart';
안쓰는 import 구문은 option+command+O로 바로 지울 수 있어여!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_history.dart
> +                "내 히스토리",
이 텍스트 뿐만 아니라 모든 TextStyle은 FarmusThemeTextStyle로 통일 부탁드립닏ㅇ!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_history.dart
> +            image: Image.asset('assets/image/ic_farmclub.png'),
여기 svg로 제가 추가해두었으니 132번 피알 머지후에 리베이스 받으셔서 해당 아이콘 변경해주셔야 할 것 같습니당

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_app_bar.dart
> +  Widget build(BuildContext context) {
해당 코드 깔끔해서 조으네요 ㅎㅎ

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +                MaterialPageRoute(builder: (context) => const MyPageProfile()),
Screen으로 이동하는 것 같은데, 페이지는 모두 ____Screen으로 통일해주시고 폴더링도 view 다음에 위치하도록 해주세용!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +              fit: BoxFit.fill,
BoxFit.cover로 바꿔주세영!
그리구 예시 이미지는 임시로 해두고 서버에서 프로필 이미지 가져오면 삭제해주셔야 할 것 같습니당

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +                      child: CircularProgressIndicator(
주석 없앱시당!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +                                (loadingProgress.expectedTotalBytes ?? 1)
우와 애니메이션인가여?!?! 애니메이션 로딩 바 색상은 primary로 해야할지 brownButton으로 할 지 디자이너님과 협의해야할 것 같네여!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +        fit: BoxFit.fill,
여기두 cover입니당!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +    return Scaffold(
Scaffold로 감싸져있으면 Screen이라, 해당 파일 Screen 취급해서 리팩토링 부탁드립니당~!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +            'assets/image/ic_arrow_left.svg',
AppBar를 커스텀한 PrimaryAppBar를 되도록 사용해주시고, 공통된 앱바 컴포넌트는 제가 따로 빼두었습니다! 뒤로가기 버튼 있는 앱 바는 따로 빼서 리팩토링 해두었는데 132피알 머지해서 해당 앱 바 사용하면 편하실거예요!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +        scrolledUnderElevation: 0,
elevation, bottomOpacity, scrolledUnderElevation은 특별한 이유가 있어서 쓰신걸까여?!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +          OnBoardingNextButton(
온보딩 다음 버튼이 프로필 수정에서 쓰이는게 불편하긴 한데, 뭔가 효율적으로 재사용 할 수 있게 리팩토링 해야겠네여 고민해보겠씁니다!

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +                  builder: (context) => const MyPageScreen(),
프로필 수정이 완료되면 해당 창이 없어지고 마이페이지로 다시 이동할 수 있도록 push가 아니라 pop을 해주셔야 합니더! 이렇게 하면 두 개의 마이페이지가 쌓여버려용

2024-03-26 15:21 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +              .read(onBoardingProfileProvider.notifier)
온보딩 프로바이더를 재사용하는 것이 맞을까여? 아예 네이밍을 바꿔야할지 고민해봐야겠네요 ㅠㅠ

2024-03-26 15:22 UTC, arinming commented
엇 지금 보니 충돌도 꽤나 나는데, 제 PR 머지되는 대로 바로바로 dev 브랜치에서 리베이스 받아주셔야 합니당..! 그래야 제 코드가 합쳐지고 코드 충돌이 발생하지 않아욥 ㅜㅜ

2024-03-27 02:39 UTC, arinming requested changes
전체적으로 1차 코드리뷰 끝났습니당 확인 부탁드려욤~~!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/component/my_page_veges.dart
> +            backgroundColor: Colors.transparent,
FarmusThemeColor 사용해주세용!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/component/my_vege_count.dart
> +        Text('$vegeCount번의 채소 재배에 성공했어요'),
깔끔하게 잘하셨어욥!!!! ㅎㅎㅎ 간결하게 잘 해두어서 해당 코드는 따로 컴포넌트로 빼지 않고 큰 컴포넌트 단위에 바로 작성해주시면 감사하겠습니당! "2개의 팜클럽에서 모든 미션을 완수했어요" 이 텍스트도 비슷한 로직일 것 같은데 이것도 통일할 수 있는 방법이 있을지 고민해봐야겠군욤 🤔

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_list.dart
> +  const FarmClubList({Key? key}) : super(key: key);
이 파일도 깔끔하게 잘 해주셨는데, 굳이 파일 뺄 필요 없이 바로 FarmClubProfile을 Column으로 감싸는 형식으로 작성해주시면 됩니당! 그리고 height 하드코딩 없어도 될 것 같습니당!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
> +  Widget _farmClubImage(String imageUrl) {
보니까 해당 위젯이 좀 반복되는 것 같은데 차라리 따로 빼서 공통으로 사용할 수 있으면 좋을 것 같습니다!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_app_bar.dart
> +    return PrimaryAppBar(
back_left_title_app_bar.dart 파일을 만들어두었는데, 해당 앱바에 텍스트만 "팜클럽 히스토리" 해주셔서 뒤로가기 버튼 있는 앱바는 재활용해주시면 감사하겠습니당~!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_box.dart
> +class MyFarmClubBox extends StatefulWidget {
StatefulWidget로 작성하신 이유가 있을까여?!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_stack_box.dart
> +  final String historyType;
비슷한 로직에 이름만 다른 클래스가 꽤나 많은 것 같은데 공통된 부분 따로 빼서 재활용할 수 있도록 해주세욥!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/my_certification_app_bar.dart
> +      leading: Row(
여기도 마찬가지로 커스텀 앱바 사용해주세용~~

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_diary_content.dart
> +                collapseText: '...닫기',
요 위젯은 어디서 사용되나용? 피그마엔 없는 것 같아서여!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_diary_feed.dart
> +            VegeDiaryPicture(
Picture 컴포넌트 빼지 않아도 될 것 같고, 컨테이너로 바로 적용해주시면 됩니당! 예시 Image도 삭제해주시고 백그라운드만 깔아주세용~~!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_diary_pic.dart
> +class VegeDiaryPicture extends StatelessWidget {
요 컴포넌트 VegiDiaryFeed에 바로 적용해주셍여!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_diary_time.dart
> +  final String postTime;
이렇게 작은 컴포넌트 단위까지 쪼개지 않으셔도 됩니당! 부모 위젯에 바로 적용해주세여

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_history_list.dart
> +final vegeInfoProvider = ChangeNotifierProvider<VegeInfoNotifier>((ref) {
프로바이더는 view_model쪽에 따로 빼서 작성해주세요!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_history_list.dart
> +  const VegeHistoryList({Key? key}) : super(key: key);
요 위젯도 26줄짜리라서 굳이 파일 뺄 필요 없는 것 같습니당!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_profile.dart
> +class VegeProfile extends ConsumerWidget {
프로필 사진이나 이미지 파일 로직 반복되는게 많아서, 공통으로 빼주세용!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/vege_diary/vege_diary_screen.dart
> +class VegeDiaryScreen extends StatefulWidget {
요 파일 Screen이라서 view 폴더에 바로 폴더링 부탁드립니당

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/vege_diary/vege_diary_list.dart
> +        child: Column(
이것도 부모 위젯에 합쳐서 작성해주세욥

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_history/vege_history_screen.dart
> +          Expanded(
스크롤 가능한 화면에 Expanded를 적용하신 이유가 궁금합니당! VegiHistoryList 컴포넌트 형식이 아니라 바로 작성부탁드려욥

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_result/vege_result_content.dart
> +                expandText: '더 보기',
이것도 피그마에서 발견하지 못했는데 어떤 위젯인가욥???

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_result/vege_result_feed.dart
> +  Widget build(BuildContext context) {
이것도 Feed 파일마다 작성되는 코드같ㅌ은데 통일해주세여!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_result/vege_result_pic.dart
> +class VegeResultPicture extends StatelessWidget {
파일이름이랑 클래스명이 다른 것들이 종종 보이는데 통일 부탁드립니당!

2024-03-27 02:39 UTC, arinming commented on lib/view/my_page/vege_result/vege_result_time.dart
> +            postTime,
이 파일도 30줄 짜리라, 부모 위젯에 적용 부탁드려용

2024-03-27 02:39 UTC, arinming commented on lib/view_model/my_page/notifier/farmclub_profile_notifier.dart
> +class FarmClubInfo {
해당 모델은 model 폴더에 따로 빼서 폴더링 해주세여!

2024-03-27 02:39 UTC, arinming commented on lib/view_model/my_page/notifier/farmclub_profile_notifier.dart
> +class FarmClubInfoNotifier extends ChangeNotifier {
ChangeNotifier는 써본적이 없는데 궁금하네여! 어떤 이유로 사용하신 걸까용?

2024-03-27 02:39 UTC, arinming commented on lib/view_model/my_page/notifier/vege_count_notifier.dart
> +final vegeCountProvider = StateNotifierProvider<VegeCountNotifier, int>((ref) {
프로바이더 파일은 따로 뺴주세욥!

2024-03-27 02:39 UTC, arinming commented on lib/view_model/my_page/notifier/vege_profile_notifier.dart
> +class VegeInfo {
여기도 마찬가지로 모델 빼주세욥!

2024-03-27 02:39 UTC, arinming commented on lib/view_model/vege_history/vege_history_provider.dart
> +// TabController를 제공하는 Provide
주석 삭제 부탁드려욥!

2024-03-27 02:39 UTC, arinming commented on lib/view_model/vege_history/vege_history_provider.dart
> +  ref.onDispose(() {
우왕 그냥 Provider도 신기하고 autoDispose도 궁금해요 저도 공부해보겠습니당~!

2024-03-27 10:49 UTC, merged

2024-03-28 09:44 UTC, geonheey commented on lib/view/my_page/vege_history/component/vege_diary_content.dart
> +                collapseText: '...닫기',
저번주 회의 때 글 길어지면 어떻게 할지에 대해 논의 한 거 반영했습니당. 근데 아직 닫기는 미정입니다!

2024-03-31 06:54 UTC, geonheey commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
> +                const TextSpan(
다시 보니 divider이 아예 없는 부분이어서 공백으로 처리했습니다~

2024-03-31 07:17 UTC, geonheey commented on lib/view/my_page/my_page_screen.dart
> +            height: 140,
이렇게 안하면 layout 오류가 생겨서 흠...방법 더 알아볼게요!

2024-03-31 07:49 UTC, geonheey commented on lib/view/my_page/component/my_history.dart
> +            image: Image.asset('assets/image/ic_farmclub.png'),
SvgPicture를 Image 위젯의 파라미터로 사용하는 것은 직접적으로 지원하지 않는다는 오류가 떠서 이건 png로 써야할 것 같아서 우선 그냥 두겠습니다!

2024-04-05 16:35 UTC, arinming reviewed
일단 리뷰 남기는데 왜 머지가 되어있는거죠...??!! 🥺ㅠㅠ 피알 따로 다시 올려야겠는데욥....>! 일단 전체적으로 Vege -> Vegi로 수정해주시고 클래스, 파일 명 안맞는것도 여전히 있어서 그 부분 확인해주세요 중요합니당.! 또한 반복되는 컴포넌트 통일이 아직 안되어있는 것 같아요 ㅜㅜ

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_history_box.dart
파일 명은 my_history_box인데 클래스 명이 MyVegeBox입니다! 필히 변경해주세요
그리고 Vege->Vegi 로 수정해주셔야 합니다!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_page_app_bar.dart
앱 바 파일은 base 폴더에 넣어주세요~

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
옵션+커맨드+L 해서 정렬 부탁합니당!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +          const Divider(thickness: 1, color: Colors.grey),
팜어스테마컬러 써주시고, 피그마 확인해서 회색 색상 맞춰주세요!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_page_veges.dart
여기도 파일명 클래스명 안맞습니다..! vege도 vegi로 수정해주시고 정렬도 같이 해주세욤

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_page_veges.dart
> +        "assets/image/img_greenonion.png",
요 이미지는 서버에서 주기로 해서 저희쪽에선 없어도 될 것 같습니다!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_vege_count.dart
이 컴포넌트 아무곳에도 안 쓰이는 것 같아요 삭제 부탁합니다!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_vege_stack_box.dart
Vege 수정해주세욘!

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/component/my_vege_stack_box.dart
> +                    TextSpan(
TextSpan 처리 굿굿입니당

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
내 채소 프로필 부분과 동일한 코드가 좀 많아보이는데 재사용할 수 있는 방법을 곰니해보는게 좋을 것 같습니당.! 일단 추후 리팩토링 해야할 것 같아여

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_widget.dart
해당 파일, 클래스의 이름이 팜클럽 위젯인데 어떤 기능을 하는지 명확히 모르겠습니다! 다른 네미잉으로 변경해주세욤

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_widget.dart
> +  final String? vegeImage;
vege 여기도 이써요

2024-04-05 16:35 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_box.dart
> +class MyFarmClubBox extends StatefulWidget {
요고 반영되었나요???