[Refactor] 마이페이지 refactoring 1차
Mojacknong/Mojacknong_Android pull request #139
Opened 2024-03-31 09:00 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #138

### 🍠 Summary
폰트 통일화
피드 사진 삭제
Screen refactoring 
등등 코드 리뷰에 있던 것들 참고해서 리팩토링 했습니다!
그리고 채소 사진들은 어떻게 빈컨테이너로 해서 백엔드에서 가져올지에 대한 이해가 완벽히 되지 않아 우선 이미지로 두었습니다.
회의 이후에 수정할 예정입니다~

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information

2024-04-07 14:13 UTC, arinming requested changes
해상도가 작은 에뮬로 돌려봤는데 오버플로우 에러가 납니다. 스크롤 적용이 아예 안되어있는 것 같은데 급하게 해결 부탁드려요..!
그리고 반복되는 코드가 정말 너무너무 많아요! ㅠㅠ 기껏 코드 잘 짜주셨는데, 한 번 잘 짜둔 코드 재사용하는 것이 개발자의 자세 아닐까요..! 피드나 프로필, 리스트 이런 부분들 다 공통화해서 재활용해주시면 훨씬 깔끔해질 것 같아요.
마지막으로 마이페이지 안에 너무나도 많은 스크린이 들어있어서 폴더의 깊이가 상당한데, 이것들도 스크린이 포함된 폴더는 view 하위에 바로 빼서 쉽게 찾을 수 있도록 폴더링 부탁드립니다.
리퀘체인지 할 테니 수정하셔서 다시 말씀해주세요! 머지는 아직입니다.

2024-04-07 14:13 UTC, arinming commented on lib/main.dart
> +      home: const MyPageScreen(),
여길 메인스크린으로 두고 메인스크린에서 바텀네비게이션으로 마이페이지 이동하는 방식으로 수정해주세용!

2024-04-07 14:13 UTC, arinming commented on lib/common/theme/farmus_theme_text_style.dart
추가 잘 하셨습니당 ㅎㅎ

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_feed/my_page_feed_content.dart
> +class MyPageFeedContent extends StatefulWidget {
이 위젯은 ExpandableText 로 인해서 Stateful로 구현하신 건가욥?! 신기하네용

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_feed/my_page_feed_screen.dart
screen 파일이 있으면, my_page_feed 라는 폴더를 view 폴더 바로 하위에 폴더링해서 해당 폴더에 옮겨주셔야 할 것 같아요. 컴포넌트까지 같이요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_feed/my_page_feed_screen.dart
> +class MyPageFeed extends StatelessWidget {
여기도 클래스 명과 파일명 안맞습니다! 스크린 파일인것같은데, 스크린은 반드시 Scaffold로 감싸서 앱바 써야해요. 이 파일은 Screen 개념은 아닌 것 같지 않나요?!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_feed/my_page_feed_screen.dart
>  import 'package:intl/intl.dart';
이건 왜 있는 건가욤?

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_feed/my_page_feed_time.dart
> +  const MyPageFeedTime({
여기 옵션 + 커맨드 + L 로 줄정렬 해주시면 완벽할 듯 싶네욤. 그리고 해당 컴포넌트 코드가 MyPageFeedContent 안에 바로 들어가도 될 정도로 간단한 것 같은데, 따로 뺀 이유가 있을까요?!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +              fit: BoxFit.cover,
저희 프로필 사진은 필수인 걸로 알고 있어요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +        fit: BoxFit.cover,
여기 코드는 어떤 이유에서 작성하신 건가용?

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/component/my_vege_stack_box.dart
notifier 활용 좋습니닷

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_certification_screen.dart
> +      appBar: const BackLeftTitleAppBar(
ㅎㅎ BackLeftTitleAppBar 활용하신거 굿굿입니당!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_certification_screen.dart
어머 너무 깔끔하네용!!!!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_history_list_screen.dart
screen 파일인데 컴포넌트 안에 있습니다..! 따로 폴더 뺴서 분리해주세욥. 그리구 Scaffold 사용은 잘 하셨는데 앱바가 어디있죠?!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_history_list_screen.dart
> +});
여기에 왜 프로바이더가 있는 건가요? 따로 분리해주세욥

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_page_screen.dart
여기는 이미 스크린인데, 바디로 FarmClubListScreen이 있는건 조금 이상하지 않을까요?!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_box.dart
여기 Stateful로 하신 이유가 있나요?!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/my_farmclub_stack_box.dart
MyFarmClubStackBox, MyVegeStackBox가 거의 똑같고, 비슷한 코드가 여러 줄 반복되고 있는 것 같은데 이 부분 해결해서 재사용해주시ㅕㄴ 좋을 것 같습니다!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/my_certification_feed.dart
>  import 'package:intl/intl.dart'; // DateFormat을 사용하기 위해 추가
주석은 불필요해 보입니당! 데이터 포맷을 위함인 건 처음 알았네요. 좋습니다 ㅎㅎ

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_list.dart
요 코드는 상위 컴포넌트에 바로 써도 될 것 같습니당! 그저 FarmClubProfile만 두 번 불러오는 코드긴 해서요

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
> +              children: <Widget>[
가독성을 위해 <Widget>을 쓰신 걸까요!? 저는 안쓰는 편이었는데, 합의해서 통일하는 게 좋을 것 같아용

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
요 코드도 MyCertificationProfile와 굉장히 비슷한 구조인데, 중복되는 부분은 하나로 통일하고 한 코드를 재사용해서 사용하는 것이 좋을 것 같아요.

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/my_certification_profile.dart
이것도 위에 언급한 profile 파일들과 같은 코드로 보여요. 같은 코드를 반복해서 쓰지 않고 재사용성을 높이는 게 개발자의 과제 아닐까요..!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/my_certification/step_title.dart
저도 이 스탭 타이틀로 재사용해야겠네요! 굿굿입니다

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/my_farmclub_screen.dart
여기의 마이팜클럽 폴더 자체를 view 하위에 바로 빼서 쉽게 찾을 수 있도록 변경해주세요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_farmclub/my_farmclub_screen.dart
> +            child: FarmClubListScreen(),
여기도 마찬가지로 마이팜클럽스크린 안에 또다른 스크린이 body로 들어가면 어색하지 않나요.?! 네이밍을 변경해주셔야 할 것 같습니다. 이 파일 안에 또 다른 Scaffold가 있는 것으로 확인이 돼요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_page_profile_screen.dart
>      ImagePicker().pickImage(source: ImageSource.gallery).then((value) {
여기부터 바텀시트 표시하는 함수까지 계속 반복이 되는 것 같아서, 제가 작업하고 있는 브랜치에서 공통화 하였는데 제 PR 머지하고 나서 같이 변경하면 좋을 것 같네용 ㅎㅎ

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_page_profile_screen.dart
> +    final hasSpecialCharacters = ref.watch(onBoardingSpecialCharactersProvider);
여기서 온보딩프로필프로바이더로 제가 만들었던 걸 재사용하는 건 좋습니다. 허나 프로바이더 이름 자체가 온보딩이기도 하고, 추후 API 연동을 고려하면 해당 프로바이더 네이밍을 profileProvider로 변경해서 재사용하는 것이 좋을 것 같네욥. 굿굿

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/my_page_profile_screen.dart
> +            borderColor: FarmusThemeColor.gray3,
여기도 온보딩 버튼이랑 동일한 것 같은데, 온보딩 버튼이 마이페이지에서 사용되니까 어색한 것 같아요. 온보딩 버튼 자체 네이밍을 바꾸든가 해야겠네요..! 그리고 피그마 반영해주셔서 버튼 색상 적용해주시고, 프로바이더 잘 쓰셨으니 프로바이더로 받아온 값에 따라 버튼 enabled 설정도 같이 해주시면 좋겠습니닷.

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_history_list.dart
이 파일도, 이 PR에서는 변경되지 않았아서 여기선 안보이지만 실제 안드로이드 스튜디오로 실행해보면 프로바이더가 그대로 남아있습니다. 따로 빼주세요! 이런 상황때문에, 계속 해당되는 피알에서 수정해서 푸시해주셔야 변경 사항을 계속 볼 수 있고 제가 코드리뷰 달기도 수월하겠죠...?!😭

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history_screen.dart
> +        title: "채소 히스토리",
피그마 확인해보시면 해당 스크린에는 아무런 타이틀이 없지 않나용?

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/vege_result/vege_result_list.dart
여기도 이미 비슷한 코드가 있는 것 같지 않나요..! 잘 짜두신 코드를 적극 활용해봅시다

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/vege_result/vege_result_feed.dart
여기도 마찬가지 입니다. 팜클럽 피드와 동일하게 컴포넌트 통일해서 재사용해주세요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/vege_diary/vege_diary_screen.dart
여기 코드는 이해하기 힘듭니다..! 탭바로 구현하신 것 같은데 다이어리 스크린으로 따로 만드신 이유가 있나요?

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/vege_diary/vege_diary_profile.dart
여기도 마찬가지로 통일부탁드려요!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/vege_diary/vege_diary_list.dart
재배결과, 성장일기 컴포넌트도 통일해서 사용해주세요. "아설레" "진짜맛있음"만 바뀌면 동일한 코드이지 않나요!?

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_profile.dart
마찬가지로 같은 코드가 4개 파일 정도에 반복되고 있어요,

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_history_tap.dart
탭바 구현 정말 잘 하신 것 같아요!!!

2024-04-07 14:13 UTC, arinming commented on lib/view/my_page/vege_history/component/vege_history_list_screen.dart
이 파일이 어디서 사용되나요?!

2024-04-08 11:31 UTC, geonheey commented on lib/view/my_page/component/my_page_feed/my_page_feed_content.dart
> +class MyPageFeedContent extends StatefulWidget {
네 맞습니다!

2024-04-08 11:34 UTC, geonheey commented on lib/view/my_page/component/my_page_feed/my_page_feed_screen.dart
> +class MyPageFeed extends StatelessWidget {
엇 다시보니 Screen 개념은 아니네요!! 수정했습니다 감사합니다 :)

2024-04-08 11:35 UTC, geonheey commented on lib/view/my_page/component/my_page_feed/my_page_feed_screen.dart
>  import 'package:intl/intl.dart';
pr올리고 제가 또 수정을 했었네요. 저건 필요없는거라 삭제했습니다~

2024-04-08 11:38 UTC, geonheey commented on lib/view/my_page/component/my_page_feed/my_page_feed_time.dart
> +  const MyPageFeedTime({
시간, 내용, 사진 세 가지로 컴포넌트를 따로 만들고 싶었습니다 :)

2024-04-15 03:57 UTC, geonheey commented on lib/view/my_page/component/my_page_info.dart
> +        fit: BoxFit.cover,
프로필 사진 필수인거 확인하고 삭제했습니다 :)

2024-04-15 03:59 UTC, geonheey commented on lib/view/my_page/my_farmclub/component/farmclub_history_list_screen.dart
screen파일 말고 컴포넌트로 변경하였습니다!

2024-04-15 10:29 UTC, geonheey commented on lib/view/my_page/my_farmclub/component/my_farmclub_box.dart
저 박스 위에 stack으로 팜클럽 프로파일 위젯이 여러개 생기는데, 그 데이터를 받아오기 위함이었슴당! 근데 stack box파일을 consumerwidget으로 해놔서 이건 stateless로 해도 될 것 같네요 감사합니다 :)

2024-04-15 10:30 UTC, geonheey commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
> +              children: <Widget>[
어떤걸 말씀하시는거죠?!

2024-04-15 10:37 UTC, geonheey commented on lib/view/my_page/my_page_profile_screen.dart
>      ImagePicker().pickImage(source: ImageSource.gallery).then((value) {
넹!!

2024-04-15 10:43 UTC, geonheey commented on lib/view/my_page/vege_history/vege_diary/vege_diary_screen.dart
중복된 코드 정리하다 보니 이 파일은 필요없다고 생각되어 삭제했습니다.

2024-04-15 13:01 UTC, arinming commented on lib/view/my_page/my_farmclub/component/farmclub_profile.dart
> +              children: <Widget>[
<Widget> 이용!

2024-05-07 09:17 UTC, arinming requested changes
dev 풀 받구, 몇 개만 수정하고 나서 푸시하고 바로 머지합시당!

2024-05-07 09:17 UTC, arinming commented on lib/view/my_farmclub/component/farmclub_history_list_screen.dart
> +class FarmClubHistoryList extends ConsumerWidget {
class 이름이 farmclub_histoy_list랑 같고 내용도 같은 것 가탕욥...! 확인 부탁드리고, 파일명 네이밍에 맞게 FarmClub -> Farmclub으로 해주셔야 할 듯합니다

2024-05-07 09:17 UTC, arinming commented on lib/view/my_farmclub/component/farmclub_profile.dart
> +                      const SizedBox(height: 6.0),
RichText랑 TextSpan 저도 익숙해지겠습니당~~!

2024-05-07 09:17 UTC, arinming commented on lib/view/my_farmclub/component/farmclub_widget.dart
> +class FarmClubWidget extends StatelessWidget {
무슨 위젯인지 명확하게 네이밍하면 더 좋을 것 같네용~~~!

2024-05-07 09:17 UTC, arinming commented on pubspec.yaml
> +  expandable_text: ^2.3.0
오 이런 기능이 있네여!

2024-05-07 09:17 UTC, arinming commented on lib/view_model/my_page/farmclub_provider.dart
여기에 팜클럽 프로바이더는 추후 farmclub 페이지 개발할 때 네이밍 중복 우려가 있어보입니다..! MyPageProvider에 따로 기능을 빼서 네이밍 해주셔야 할 것 같아요

2024-05-07 09:17 UTC, arinming commented on lib/view/my_page/my_page_feed/my_page_feed_content.dart
> +              ),
ExpandableText 직관적이고 좋은데여!

2024-05-07 09:17 UTC, arinming commented on lib/view/my_page/my_page_screen.dart
> +        ),
이 부분 height 하드코딩 하신 이유가 뭘까요?!

2024-05-07 09:17 UTC, arinming commented on lib/view/my_page/feed_screen.dart
appbar가 없는 것 같은데, 여기서 scaffold를 쓰신 이유가 있을까요? 이유가 없다면 지워주시고, screen이라는 네이밍도 다르게 변경해주셔야 할 것 같아요!

2024-05-07 09:17 UTC, arinming commented on lib/view/my_page/component/my_divider.dart
> +  Widget build(BuildContext context) {
divider는 굳이 컴포넌트로 안 나누고 바로 사용해도 될 것 같습니다.!

2024-05-07 14:02 UTC, arinming approved these changes
길었던 리팩토링 수고했어요 너무너무!!!!!!!

2024-05-07 14:04 UTC, merged