[Feat] 탐색 탭의 첫 페이지 UI 구현
Mojacknong/Mojacknong_Android pull request #153
Opened 2024-05-08 14:13 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #148

### 🍠 Summary
탭 바, 난이도, 팜클럽 정보가 있는 위젯을 구현하였습니다!

https://github.com/Mojacknong/Farmus_App/assets/105162858/90ac3012-a865-4007-b6ab-910be1619c10

### 🌽 PR Type
- [x] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information

2024-05-09 15:22 UTC, arinming commented on assets/image/ic_alert_circle_black.svg
요 아이콘은 SvgPicture에서 colorfilter.mode로 색상을 바꿀 수 있어서 지워주시고, ic_alert_circle을 그대로 사용해주세용

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_app_bar.dart
아니 너무 깔끔하닷 최고

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_app_bar.dart
> +              padding: const EdgeInsets.only(left: 16.0),
왼쪽만 패딩 준 이유가 있을까여!?

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_difficulty_box.dart
> +            height: 63,
해당 파일에서 height 하드코딩은 최대한 피해봅시당 padding, margin으로 구현해보시겠어용?

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_difficulty_btn.dart
> +    }
이렇게 케이스로 나누니 좋으네용

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_difficulty_btn.dart
> +        height: 31,
여기두 하드코딩 있어요!

2024-05-09 15:22 UTC, arinming commented on lib/view/search/search_screen.dart
> +                    padding: EdgeInsets.only(left: 16.0),
horizontal로 양쪽 다 패딩을 넣어주는 거 어떨까요!

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_welcome_text.dart
> +      height: 130,
하드코딩..! 오버플로우가 날 수 있기 때문에 피해주셔야 합니다
margin, padding 사용해주세요!

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_vege_info.dart
> +              overflow: TextOverflow.ellipsis,
이건 어떤 기능인가요?

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_farmclub_info_widget.dart
> +                  ),
${}를 사용해서 한 줄로 표현할 수 있지 않을까요?

2024-05-09 15:22 UTC, arinming commented on lib/view/search/component/search_vege_info.dart
> +            bottomWidget: const Text(
Text에 수직 패딩도 넣으면 좋을 것 같아요!

2024-05-09 18:50 UTC, arinming requested changes
Search, MyPage, Farmclub이 전부 팜어스 로고가 leading이어서, action 기능만 추가할 수 있도록 재활용하는 게 좋을 것 같아요. 해당 앱 바 만들어서 올려둘테니 Search, MyPage 앱바 일일이 구현하는 것 대신 팜어스로고앱바 사용해주ㅅ[여!!

2024-05-10 02:42 UTC, geonheey commented on lib/view/search/component/search_app_bar.dart
> +              padding: const EdgeInsets.only(left: 16.0),
그래야 파머스로고가 제위치에 옵니당! 패딩 안주면 화면왼쪽에 바로 따닥 붙어있어용

2024-05-10 02:53 UTC, geonheey commented on assets/image/ic_alert_circle_black.svg
오 이런 방법이 있었네요 감사합니다 :)

2024-05-10 03:12 UTC, geonheey commented on lib/view/search/component/search_welcome_text.dart
> +      height: 130,
Column속성으로 넓이와 높이를 따로 정해줄 필요가 없었네요!! 덕분에 필요없는 코드 삭제했습니다ㅎㅎ

2024-05-10 03:12 UTC, geonheey commented on lib/view/search/component/search_vege_info.dart
> +              overflow: TextOverflow.ellipsis,
2줄이 넘어가면 ...으로 생략하는 기능입니다 :)

2024-05-10 03:44 UTC, geonheey commented on lib/view/search/component/search_vege_info.dart
> +            bottomWidget: const Text(
수직패딩으로 하면 패딩이 너무 적게 들어가서 top으로 10넣어줬습니당 패딩 넣으니까 훨씬 보기 좋네요!

2024-05-10 06:42 UTC, arinming commented on lib/view/search/component/search_app_bar.dart
> +              padding: const EdgeInsets.only(left: 16.0),
왼쪽만! 준 이유가 궁금합니다
horizontal로 해주세요!

2024-05-10 06:48 UTC, arinming commented on lib/view/search/component/search_vege_info.dart
> +              overflow: TextOverflow.ellipsis,
배워겁니다..!

2024-05-10 07:36 UTC, arinming approved these changes
성장하시는 게 눈에 보여요 🥹 파이팅 !!!!

2024-05-10 07:36 UTC, arinming commented on lib/view/search/component/search_difficulty_box.dart
> +          Align(
우왕 이렇게 Align으로 사용하기도 하는군요!

2024-05-10 07:36 UTC, arinming commented on lib/view/search/component/search_difficulty_btn.dart
> +  Widget build(BuildContext context) {
여기 Stateful로 사용하신 이유가 있나여?

2024-05-10 07:36 UTC, arinming commented on lib/view/search/component/search_farmclub_info_widget.dart
> +                  ),
깔끔하게 잘하셨네여 ㅎㅎ

2024-05-11 05:29 UTC, geonheey commented on lib/view/search/component/search_difficulty_btn.dart
> +  Widget build(BuildContext context) {
버튼 클릭 시, state가 바뀐다고 생각이들어 stateful로 사용을 했습니다!

2024-05-11 06:56 UTC, arinming requested changes

2024-05-11 06:56 UTC, arinming commented on lib/view/search/component/search_app_bar.dart
이 서치 앱 바 없애주시고, 뷰에 farmusLogoAppBar 바로 사용해주세요!

2024-05-11 06:56 UTC, arinming commented on lib/view/my_page/component/my_page_app_bar.dart
이 앱 바도 마찬가지로 삭제해주시고 바로 팜어스로고앱바 사용해주세요!

2024-05-11 09:38 UTC, arinming approved these changes
고생해써요~~~!!~ 점점 깔끔해지는 코드 🥳

2024-05-11 09:40 UTC, merged