[Feat] 루틴 UI 구현
Mojacknong/Mojacknong_Android pull request #154
Opened 2024-05-09 18:46 UTC by arinming

### 🥕 Issue number and Link
이슈 번호 : #152 

### 🍠 Summary
- 루틴 추가 바텀 시트 구현
- 루틴 수정 바텀 시트 구현 (최대한 추가 바텀 시트 재활용)
- 루틴 체크박스 구현
- 스위치에 따라 텍스트필드 입력 가능 여부 구현

https://github.com/Mojacknong/Farmus_App/assets/97820109/4559be70-3262-44d1-b26b-89fe8fa6b34c

### 🌽 PR Type
- [x] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information
바텀 시트부터  체크 박스... 진짜 이번 UI 너무 빡셌습니다!!!!!!! ㅠㅠ
루틴 추가 or 수정에 따라 바텀 시트를 달리 해야하는데 최대한 재활용하려고 했습니다 그래도 코드 맘에 안드는.....

2024-05-10 04:05 UTC, geonheey requested changes

2024-05-10 04:05 UTC, geonheey commented on lib/common/app_bar/farmus_logo_app_bar.dart
이 앱 바 마이페이지와 탐색 탭에 재사용하겠습니다. 감사합니당 ㅎㅎ

2024-05-10 04:05 UTC, geonheey commented on lib/view/home/component/home_vege_routine.dart
>      return toDo == "routine"
엇 이 파일은 return toDo == "routine" 이렇게 해줌으로써 어떤 기능을 수행하는건가요?! 자주보던 구조가 아니라 신기하네요..!

2024-05-10 04:05 UTC, geonheey commented on lib/view/home/component/vege_routine.dart
쉽지 않았을 것 같은 vege_routine.dart...

2024-05-10 04:05 UTC, geonheey commented on lib/view/routine/component/routine_bottom_sheet_content.dart
> +                      PrimarySwitch(
저 설정에서 switch 만들었었는데 primaryswitch로 통일할까요?? 
그리고 애니메이션이 있는 것 같던데 디자이너와 따로 이야기를 해봐야할까요?

2024-05-10 04:05 UTC, geonheey commented on lib/view/vege_add/component/vege_add_calender.dart
>    ConsumerState createState() => _VegeAddCalenderState();
엇 여기는 _VegeAddCalenderState로 되어있습니당 !

2024-05-10 04:05 UTC, geonheey commented on lib/view_model/routine/routine_provider.dart
루틴 너무너무 고생 많으셨습니다ㅠㅠ

2024-05-10 06:44 UTC, arinming commented on lib/view/home/component/home_vege_routine.dart
>      return toDo == "routine"
팜클럽 미션/오늘 할 일 이렇게 나뉘어서 버튼 선택시 다른 컴포넌트를 보여줘야 해가지구
todo -> routine인 경우에는 오늘 할 일의 루틴을 보여주도록 구현했스비다!

2024-05-10 06:44 UTC, arinming commented on lib/view/home/component/vege_routine.dart
🥹😭🥹😭🥹😭🥹😭🥹😭

2024-05-10 06:45 UTC, arinming commented on lib/view/routine/component/routine_bottom_sheet_content.dart
> +                      PrimarySwitch(
넵! 통일하면 좋을 것 같습니당.
해당 스위치가 플러터에서 기본적으로 제공하는 스위치여서, 기본적으로 애니메이션이 들어가있어요! 회의때 얘기해보겠습니다

2024-05-10 06:45 UTC, arinming commented on lib/view/vege_add/component/vege_add_calender.dart
>    ConsumerState createState() => _VegeAddCalenderState();
매의 눈..>!

2024-05-11 05:03 UTC, geonheey approved these changes

2024-05-11 05:04 UTC, merged