[Feat] 팜클럽 난이도 필터링 API 연동
Mojacknong/Mojacknong_Android pull request #188
Opened 2024-06-03 10:29 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #185

### 🍠 Summary
난이도 버튼에 따라 팜클럼이 필터링 되게 API연동을 하였습니다.
현재 사진은 임시로 둔 것이고 회의 때 디자이너와 PM님과 이야기하여 추후에 리팩토링 진행하겠습니다.

https://github.com/Mojacknong/Farmus_App/assets/105162858/da7b7cf7-e029-4031-8033-913325fd1ea6

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information
아린님께서 올려두신 레퍼런스 보았는데 난이도 필터링 API연동 부분에서는 필수적이지 않은 것 같아 그거 제외하고 다른 양식은 모두 맞췄습니다!!
만약 이 부분에서 꼭 레퍼런스의 양식을 가져가야한다면 전시회가 끝나고 맞추는건 어떠신지 조심스럽게 여쭤봅니다...
당장 이번주 전시회에 다음 주가 기말고사라 ㅠㅠ

2024-06-03 17:45 UTC, arinming requested changes
공식문서대로 요청해봅시다..!

2024-06-03 17:45 UTC, arinming commented on lib/model/search/farmclub_help_info_model.dart
get 요청은 factory 형식으로 모델링하더라구요.

https://riverpod.dev/ko/docs/essentials/first_request

해당 공식문서 참고해서 바꿨는데
187번 브랜치에서 추천 채소 받아오는 걸로 제가 적용해두긴 했습니다! 참고해서 리팩토링 해보실래용?

2024-06-03 17:45 UTC, arinming commented on lib/view/search/component/search_farmclub_pic.dart
> +    print('이미지파일: $imageUrl');
프린트문 삭제 부탁드립니당~!

2024-06-03 17:45 UTC, arinming commented on lib/view/search/component/search_farmclub_pic.dart
> +          )),
편----안한 코드네여

2024-06-03 17:45 UTC, arinming commented on lib/view_model/farmclub_sign_up/farmclub_sign_up_provider.dart
> +});
https://riverpod.dev/ko/docs/essentials/first_request

요 공식문서 참고해서 구현해주셔야 할 듯 합니다.
그리고 SearchFarmclubService에서 바로 가져오는 것이 아니라,
서버에서 작성해준 명세서에 따라 FarmclubRepository를 만들어주시고
거기에서 서비스 접근해주세요!

그리고 FarmclubRepository 접근은 노티파이어나 riverpod 프로바이더 사용해서 접근해주세요 공식문서 어렵지만 꼼꼼히 봐주셔야 합니다 ㅜㅜ

2024-06-04 00:07 UTC, geonheey commented on lib/view_model/farmclub_sign_up/farmclub_sign_up_provider.dart
> +});
넵!! 빠르게 리팩토링해서 다시 푸시하겠습니다 :)

2024-06-05 02:40 UTC, arinming approved these changes
필터링 어려우셨을 텐데 고생하셨습니다 ㅠㅠ riverpod 관련된 부분만 빠르게 수정하구 머지하면 될 것 같아요~~! 일단 riverpod는 우선순위가 높아서...! 바쁘지만 하나하나 나중에 리팩하는 것보다 지금 하나를 제대로 해두면 뒤에 남은 API 연동도 같은 형식으로 통일할 수 있지 않을까 싶습니당.!

2024-06-05 02:40 UTC, arinming commented on lib/model/search/search_farmclub_detail_model.dart
> +  factory SearchFarmclubDetailModel({
freezed 사용 조아요~~~!

2024-06-05 02:40 UTC, arinming commented on lib/view/search_farmclub/search_farmclub_screen.dart
>    const SearchFarmclubScreen({Key? key}) : super(key: key);
ConsumerStatefulWidget로 설정하신 이유가 궁금합니다~!

2024-06-05 02:40 UTC, arinming commented on lib/view_model/farmclub_sign_up/farmclub_sign_up_provider.dart
> +});
riverpod 사용하시면 없어도 되는 코드 아닐까여?!

2024-06-05 02:40 UTC, arinming commented on lib/view_model/search/search_provider.dart
> +}
요 코드는 따로 파일 분리해주시는게 좋을 것 같아요!

2024-06-05 09:17 UTC, arinming approved these changes
주석 삭제해주고 텃받->텃밭으로 고쳐서 바로 머지해주세용!

2024-06-05 09:17 UTC, arinming commented on lib/common/bottom_sheet/show_farmus_bottom_sheet.dart
>        ? "내 텃받에 등록된 채소로만 가입할 수 있어요\n새 채소를등록해보세요!"
텃밭으로 고쳐야할듯욤..!

2024-06-05 10:10 UTC, merged