[Feat] 프로필 정보 조회 API 연동
Mojacknong/Mojacknong_Android pull request #226
Opened 2024-08-02 18:28 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #222

### 🍠 Summary
프로필 정보 조회 API 연동 완료하였습니다~
![스크린샷 2024-08-03 오전 3 27 24](https://github.com/user-attachments/assets/71bdd710-de7b-4738-9334-607b198a7fe5)

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information

2024-08-05 07:50 UTC, arinming requested changes
리뷰 확인해주시면 감사하겠습니당!

2024-08-05 07:50 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +    final myPageInfoAsyncValue = ref.watch(myPageInfoModelProvider);
여기 StatefulWidget으로 한 이유가 있을까요??

2024-08-05 07:50 UTC, arinming commented on lib/view/my_page/component/my_page_info.dart
> +                          height: 68,
흠 여기 하드코딩말구 다른 방법 없을까용,.,>~!
없다면 FarmusPicture으로 위젯 대체해주시면 감사하겠습니다!

2024-08-05 07:50 UTC, arinming commented on lib/view_model/my_page/my_page_info_provider.dart
> +    }
여기서 nickName, userImageUrl를 String으로 타입 변경한 이유가 있나요??!

2024-08-06 07:48 UTC, geonheey commented on lib/view_model/my_page/my_page_info_provider.dart
> +    }
앗 수정하려다가 까먹고 있었네요 감사합니다 :)

2024-08-07 08:43 UTC, arinming approved these changes
확인했습니다~ 풀 꼭 받고 푸시까지 해주시고 머지 부탁드려요

그리고 제 피알도 리뷰 남겨주세요..!

2024-08-07 08:54 UTC, merged