[Feat] 프로필 정보 수정 API 연동
Mojacknong/Mojacknong_Android pull request #233
Opened 2024-08-09 06:00 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #227

### 🍠 Summary
프로필 수정 API 연동을 하였습니다.
피그마에서는 수정 또한 사진, 닉네임 모두 수정해야 완료되는걸로 되어있어 그렇게 구현하였는데
닉네임이나 이미지만 바꿔도 수정이 가능하는게 나은 것 같아서 이 부분 회의 때 이야기해봐야할 것 같습니다!

https://github.com/user-attachments/assets/e5f516e0-8b93-42f7-911c-223a12b09d9a

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information

2024-08-10 08:38 UTC, arinming requested changes
수고하셨어요! 수정사항 확인해주세용

2024-08-10 08:38 UTC, arinming commented on lib/data/network/base_api_services.dart
> +        }
POST_MULTIPART가 일기, 미션 등록할 때도 사용될텐데 base_api_services에서 nickname과 프로필이미지를 직접적으로 다루는 건 수정해주세요..!

2024-08-10 08:38 UTC, arinming commented on lib/data/network/base_api_services.dart
> +        print('베이스 api: ${utf8.decode(response.bodyBytes)}');
print 되는 부분이 여기저기 많이 있는데 일괄적으로 삭제 부탁드립니다. 디버깅 모드 사용해주세요!

2024-08-10 08:38 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +            .updateProfileImage(pickedFile);
my_page_profile에서 onBoardingProfileSetProvider이라는 네이밍의 노티파이어를 사용하시는 이유가 있나용.....??

2024-08-10 08:38 UTC, arinming commented on lib/view/on_boarding/component/on_boarding_nickname_text_input.dart
> +class OnBoardingNicknameTextInput extends ConsumerStatefulWidget {
온보딩 닉네임 텍스트 폼을 바꾸신 이유가 있나요....????!!!

2024-08-10 08:38 UTC, arinming commented on lib/view_model/my_page/notifier/my_page_info_change_notifier.dart
> +  }
이 함수들을 my_page_user_profile_model_notifier에서 합쳐서 사용하면 좋을 것 같아요.
루틴 바텀 시트 노티파이어 참고하시면 이해하기 수월하실 거예요!

2024-08-12 09:05 UTC, geonheey commented on lib/view/on_boarding/component/on_boarding_nickname_text_input.dart
> +class OnBoardingNicknameTextInput extends ConsumerStatefulWidget {
네 이게 프로필 수정할 때 원래 설정했던 닉네임 글자수가 인식이 안되고 0으로 무조건 시작해서 원래 닉네임 글자수까지 인식하도록 했습니다!

2024-08-12 09:07 UTC, geonheey commented on lib/view/my_page/component/my_page_profile.dart
> +            .updateProfileImage(pickedFile);
온보딩 때 설정했던 것을 인식할 수 있게 + 재사용이라고 봐주시면 될 것 같습니다~

2024-08-14 01:32 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +            .updateProfileImage(pickedFile);
닉네임을 따로 서버에서 요청해서 받아오셔서 마이페이지 용 노티파이어를 따로 사용해주셔야 할 것 같습니다.
온보딩 노티파이어를 마이페이지에서 그대로 사용하는 건 어색한 것 같지 않나요..!🥺

2024-08-14 01:32 UTC, arinming commented on lib/view/on_boarding/component/on_boarding_nickname_text_input.dart
> +class OnBoardingNicknameTextInput extends ConsumerStatefulWidget {
닉네임을 따로 서버에서 요청해서 받아오셔서 사용하면 동일하게 해결 가능하지 않을까요...?! 온보딩 텍스트 폼은 온보딩에서만 사용하도록 분리해주셨으면 합니다.

2024-08-14 01:40 UTC, arinming requested changes

2024-08-14 01:40 UTC, arinming commented on lib/view/my_page/component/my_page_profile.dart
> +            .updateProfileImage(pickedFile);
아니면 리네임을 하는 방식으로 바꿔야할 것 같아요..!

2024-08-15 07:46 UTC, geonheey commented on lib/view/on_boarding/component/on_boarding_nickname_text_input.dart
> +class OnBoardingNicknameTextInput extends ConsumerStatefulWidget {
닉네임은 따로 서버에서 요청했는데 인식이 안됐습니다 프로필 수정용 따로 만들겠습니다.

2024-08-15 09:26 UTC, arinming approved these changes
고생하셨어요~!

2024-08-15 11:11 UTC, merged