[Feat] 팜클럽 히스토리 관련 모든 API 연동 완료
Mojacknong/Mojacknong_Android pull request #238
Opened 2024-08-12 15:50 UTC by geonheey

### 🥕 Issue number and Link
이슈 번호 : #237

### 🍠 Summary
- 유저 히스토리 조회 - 팜클럽 API
- 팜클럽 히스토리 목록 조회 API
- 팜클럽 히스토리 단일 조회 API
위 3가지 API 모두 연동하였습니다.

https://github.com/user-attachments/assets/6079f906-fd0a-4e0c-b077-6621d407fc8b

### 🌽 PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Code Style Update
- [ ] Refactoring
- [ ] Documentation content change
- [ ] Other

### 🫛 Other Information
추가로 디자인쪽에서 나의 인증 이미지 height를 고정하여 피드 이미지가 일정한 사이즈로 보이고 그 사이즈에 맞춰 이미지가 잘리도록 요청하셔서 height를 고정하였습니다!

2024-08-14 01:59 UTC, arinming commented on lib/data/network/my_farmclub_history_service.dart
myFarmclubHistoryService랑 myHistoryService를 파일 단위로 나누신 이유가 있을까요? 같은 분류로 마이페이지 서비스라고 생각이 됩니다. 마이페이지 서비스 안에서 다뤄도 될 것 같아요!

2024-08-14 01:59 UTC, arinming commented on lib/data/network/my_history_service.dart
> +        farmClubHistoryIcons: farmClubHistoryIcons,
노티파이어에서 나누지 않고 서비스단에서 데이터를 타입별로 나누신 이유가 있으신가요?

2024-08-14 01:59 UTC, arinming commented on lib/repository/my_farmclub_history_repository.dart
리포지토리 단위도 마찬가지로 통합할 수 있을 것 같습니다.

2024-08-14 01:59 UTC, arinming commented on lib/view/my_page/my_page_feed/my_page_feed_picture.dart
>  import 'package:flutter/material.dart';
미션 피드, 일기 등에서 동일한 사진 컴포넌트를 사용하고 있는데 확인 부탁드려요!

2024-08-14 01:59 UTC, arinming commented on lib/view_model/my_page/my_history_farmclub_provider.dart
지금까지 notifier로 통일해왔는데, provider로 네이밍하신 이유가 궁금합니다!

2024-08-15 08:56 UTC, geonheey commented on lib/view/my_page/my_page_feed/my_page_feed_picture.dart
>  import 'package:flutter/material.dart';
엇 확인해서 삭제하고 FarmusPictureFix 재사용했습니다 감사합니다 :)

2024-08-15 08:57 UTC, geonheey commented on lib/data/network/my_history_service.dart
> +        farmClubHistoryIcons: farmClubHistoryIcons,
리뷰 보고 코드 수정하다 더 간결한 코드가 나와서 변경하였습니다!

2024-08-15 09:29 UTC, arinming requested changes
몇가지 수정사항만 고치고 바로 머지하셔도 될 것 같습니다~!

2024-08-15 09:29 UTC, arinming commented on lib/view_model/my_farmclub_history/my_farmclub_certification_provider.dart
여기도 프로바이더입니다!

2024-08-15 09:29 UTC, arinming commented on lib/data/network/my_history_service.dart
> +  }
내 팜클럽 히스토리 로 수정부탁드려요!

2024-08-15 11:11 UTC, merged